name: ZeusMode
version: 0.2.0
main: thenewherobrine.zeusmode.Main
author: TheNewHEROBRINE

commands:
 zeusmode:
  description: "Toggle ZeusMode"
  usage: "/zeusmode <on|off> [ticks]"
  permission: zeusmode.command.zeusmode
  
 lightning:
  description: "strike a lightning"
  usage: "/lightning [player] or /lightning <x> <y> <z> [world]"
  permission: zeusmode.command.lightning
  
permissions:
 zeusmode.*:
  children:
   zeusmode.command.*: true
 
 zeusmode.command.*:
  children:
   zeusmode.command.zeusmode: true
   zeusmode.command.lightning: true
 
 zeusmode.command.zeusmode:
  default: op
  
  zeusmode.command.lightning:
  default: op
